actor: AcceptanceTester
modules:
   enabled:
      - WebDriver:
         url: 'http://localhost:8888' # Site URL
         browser: chrome
         port: '9515'
         window_size: false
         capabilities:
          chromeOptions:
            #args: ["--headless", "--disable-gpu"]
            #binary: "chrome"
            binary: "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome" # Path to Chrome binary
            #binary: "//Applications/MAMP/htdocs/wp-content/plugins/parler-wordpress-php/chromedriver"